FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

# In dev, we bind mount source code, so we don't copy it here
# Just expose port and command
EXPOSE 3000

CMD ["npm", "run", "start:dev"]
