import { CandidateListItem } from '@/types/candidate-list';
import { subDays, subHours } from 'date-fns';

const now = new Date();

export const mockRecruiters = [
  { id: 'rec-1', name: 'Priya Sharma' },
  { id: 'rec-2', name: 'Sarah Chen' },
  { id: 'rec-3', name: 'Mike Johnson' },
];

export const mockSources = [
  'LinkedIn',
  'Indeed',
  'Referral',
  'Website',
  'Job Board',
];

export const mockCandidateList: CandidateListItem[] = [
  {
    id: 'cand-1',
    name: 'Alex Rivera',
    email: 'alex.rivera@gmail.com',
    phone: '+1-555-0101',
    role: 'Senior Frontend Engineer',
    stage: 'screening',
    source: 'LinkedIn',
    recruiterName: 'Priya Sharma',
    recruiterId: 'rec-1',
    lastActivity: subHours(now, 2).toISOString(),
    lastActivityType: 'interview',
    dateAdded: subDays(now, 14).toISOString(),
    skills: ['React', 'TypeScript', 'Node.js'],
    experienceYears: 5,
    tenantId: 'tenant_123',
  },
  {
    id: 'cand-2',
    name: 'Emma Watson',
    email: 'emma.watson@outlook.com',
    phone: '+1-555-0102',
    role: 'Product Manager',
    stage: 'interview-1',
    source: 'Referral',
    recruiterName: 'Sarah Chen',
    recruiterId: 'rec-2',
    lastActivity: subHours(now, 5).toISOString(),
    lastActivityType: 'email',
    dateAdded: subDays(now, 7).toISOString(),
    skills: ['Product Strategy', 'Agile', 'Analytics'],
    experienceYears: 6,
    tenantId: 'tenant_123',
  },
  {
    id: 'cand-3',
    name: 'James Park',
    email: 'james.park@yahoo.com',
    phone: '+1-555-0103',
    role: 'Backend Developer',
    stage: 'interview-2',
    source: 'Job Board',
    recruiterName: 'Mike Johnson',
    recruiterId: 'rec-3',
    lastActivity: subDays(now, 1).toISOString(),
    lastActivityType: 'note',
    dateAdded: subDays(now, 21).toISOString(),
    skills: ['Python', 'AWS', 'PostgreSQL'],
    experienceYears: 4,
    tenantId: 'tenant_123',
  },
  {
    id: 'cand-4',
    name: 'Sofia Martinez',
    email: 'sofia.martinez@gmail.com',
    phone: '+1-555-0104',
    role: 'Data Analyst',
    stage: 'offer',
    source: 'Website',
    recruiterName: 'Priya Sharma',
    recruiterId: 'rec-1',
    lastActivity: subHours(now, 8).toISOString(),
    lastActivityType: 'stage-change',
    dateAdded: subDays(now, 28).toISOString(),
    skills: ['SQL', 'Python', 'Tableau'],
    experienceYears: 3,
    tenantId: 'tenant_123',
  },
  {
    id: 'cand-5',
    name: 'David Kim',
    email: 'david.kim@proton.me',
    phone: '+1-555-0105',
    role: 'DevOps Engineer',
    stage: 'screening',
    source: 'Indeed',
    recruiterName: 'Sarah Chen',
    recruiterId: 'rec-2',
    lastActivity: subDays(now, 2).toISOString(),
    lastActivityType: 'created',
    dateAdded: subDays(now, 5).toISOString(),
    skills: ['Kubernetes', 'Docker', 'Terraform'],
    experienceYears: 4,
    tenantId: 'tenant_123',
  },
];
