import { Integration, FieldMapping, IntegrationField, WebhookEvent, IntegrationError, IntegrationMetrics } from '@/types/integrations';

export const providerLogos: Record<string, string> = {
  salesforce: '/integrations/salesforce.png',
  hubspot: '/integrations/hubspot.png',
  zoho: '/integrations/zoho.png',
  workday: '/integrations/workday.png',
  lever: '/integrations/lever.png',
  greenhouse: '/integrations/greenhouse.png',
  bamboohr: '/integrations/bambooHR.png',
  google_calendar: '/integrations/GC.png',
  outlook_calendar: '/integrations/OC.png',
  custom: '/integrations/lever.png',
};

export const providerColors: Record<string, string> = {
  salesforce: 'bg-blue-500',
  hubspot: 'bg-orange-500',
  zoho: 'bg-red-500',
  workday: 'bg-indigo-500',
  lever: 'bg-green-500',
  greenhouse: 'bg-emerald-500',
  bamboohr: 'bg-lime-600',
  google_calendar: 'bg-blue-600',
  outlook_calendar: 'bg-sky-600',
  custom: 'bg-gray-500',
};

export const providerDocs: Record<string, string> = {
  salesforce: 'https://developer.salesforce.com/docs',
  hubspot: 'https://developers.hubspot.com/docs',
  zoho: 'https://www.zoho.com/developer/help',
  workday: 'https://community.workday.com/developers',
  lever: 'https://hire.lever.co/developer',
  greenhouse: 'https://developers.greenhouse.io',
  bamboohr: 'https://documentation.bamboohr.com/docs',
  google_calendar: 'https://developers.google.com/calendar',
  outlook_calendar: 'https://learn.microsoft.com/en-us/graph/outlook-calendar-concept-overview',
};

export const mockIntegrations: Integration[] = [
  {
    id: 'int-001',
    tenantId: 'tenant-001',
    provider: 'salesforce',
    name: 'Salesforce CRM',
    description: 'Sync candidates and jobs with Salesforce',
    status: 'connected',
    authType: 'oauth2',
    supportedObjects: ['Candidates', 'Jobs', 'Contacts', 'Accounts'],
    lastSyncAt: new Date(Date.now() - 15 * 60 * 1000),
    nextSyncAt: new Date(Date.now() + 45 * 60 * 1000),
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date(),
    config: {
      syncDirection: 'bidirectional',
      syncCadence: '1hour',
      conflictResolution: 'latest_wins',
      enableWebhooks: true,
      webhookUrl: 'https://api.example.com/webhooks/salesforce',
    },
  },
  {
    id: 'int-002',
    tenantId: 'tenant-001',
    provider: 'greenhouse',
    name: 'Greenhouse ATS',
    description: 'Import candidates and applications from Greenhouse',
    status: 'connected',
    authType: 'api_key',
    supportedObjects: ['Candidates', 'Applications', 'Jobs', 'Stages'],
    lastSyncAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    nextSyncAt: new Date(Date.now() + 4 * 60 * 60 * 1000),
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date(),
    config: {
      syncDirection: 'inbound',
      syncCadence: '6hours',
      conflictResolution: 'source_wins',
      enableWebhooks: true,
    },
  },
  {
    id: 'int-003',
    tenantId: 'tenant-001',
    provider: 'hubspot',
    name: 'HubSpot CRM',
    description: 'Sync contacts and deals with HubSpot',
    status: 'error',
    authType: 'oauth2',
    supportedObjects: ['Contacts', 'Deals', 'Companies'],
    lastSyncAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date(),
    config: {
      syncDirection: 'outbound',
      syncCadence: 'daily',
      conflictResolution: 'target_wins',
      enableWebhooks: false,
    },
  },
  {
    id: 'int-004',
    tenantId: 'tenant-001',
    provider: 'lever',
    name: 'Lever ATS',
    description: 'Pending authentication',
    status: 'pending_auth',
    authType: 'oauth2',
    supportedObjects: ['Candidates', 'Opportunities', 'Postings'],
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date(),
  },
  {
    id: 'int-005',
    tenantId: 'tenant-001',
    provider: 'workday',
    name: 'Workday HCM',
    description: 'Sync employee data with Workday',
    status: 'disconnected',
    authType: 'oauth2',
    supportedObjects: ['Workers', 'Positions', 'Organizations'],
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date(),
  },
  {
    id: 'int-006',
    tenantId: 'tenant-001',
    provider: 'bamboohr',
    name: 'BambooHR',
    description: 'Employee and HR data sync',
    status: 'syncing',
    authType: 'api_key',
    supportedObjects: ['Employees', 'Time Off', 'Benefits'],
    lastSyncAt: new Date(),
    createdAt: new Date('2024-05-20'),
    updatedAt: new Date(),
    config: {
      syncDirection: 'inbound',
      syncCadence: 'realtime',
      conflictResolution: 'source_wins',
      enableWebhooks: true,
    },
  },
  {
    id: 'int-007',
    tenantId: 'tenant-001',
    provider: 'google_calendar',
    name: 'Google Calendar',
    description: 'Sync interview schedules with Google Calendar',
    status: 'disconnected',
    authType: 'oauth2',
    supportedObjects: ['Events', 'Calendars'],
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date(),
  },
  {
    id: 'int-008',
    tenantId: 'tenant-001',
    provider: 'outlook_calendar',
    name: 'Outlook Calendar',
    description: 'Sync interview schedules with Microsoft Outlook',
    status: 'disconnected',
    authType: 'oauth2',
    supportedObjects: ['Events', 'Calendars'],
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date(),
  },
];

export const mockSourceFields: IntegrationField[] = [
  { name: 'first_name', type: 'string', label: 'First Name', required: true },
  { name: 'last_name', type: 'string', label: 'Last Name', required: true },
  { name: 'email', type: 'email', label: 'Email Address', required: true },
  { name: 'phone', type: 'phone', label: 'Phone Number', required: false },
  { name: 'company', type: 'string', label: 'Company Name', required: false },
  { name: 'title', type: 'string', label: 'Job Title', required: false },
  { name: 'created_date', type: 'datetime', label: 'Created Date', required: true },
  { name: 'status', type: 'picklist', label: 'Status', required: true },
];

export const mockTargetFields: IntegrationField[] = [
  { name: 'firstName', type: 'string', label: 'First Name', required: true },
  { name: 'lastName', type: 'string', label: 'Last Name', required: true },
  { name: 'emailAddress', type: 'email', label: 'Email', required: true },
  { name: 'phoneNumber', type: 'phone', label: 'Phone', required: false },
  { name: 'organization', type: 'string', label: 'Organization', required: false },
  { name: 'position', type: 'string', label: 'Position', required: false },
  { name: 'createdAt', type: 'datetime', label: 'Created At', required: true },
  { name: 'candidateStatus', type: 'picklist', label: 'Candidate Status', required: true },
];

export const mockFieldMappings: FieldMapping[] = [
  { id: 'map-001', integrationId: 'int-001', sourceField: 'first_name', sourceType: 'string', targetField: 'firstName', targetType: 'string', required: true, validated: true },
  { id: 'map-002', integrationId: 'int-001', sourceField: 'last_name', sourceType: 'string', targetField: 'lastName', targetType: 'string', required: true, validated: true },
  { id: 'map-003', integrationId: 'int-001', sourceField: 'email', sourceType: 'email', targetField: 'emailAddress', targetType: 'email', required: true, validated: true },
  { id: 'map-004', integrationId: 'int-001', sourceField: 'phone', sourceType: 'phone', targetField: 'phoneNumber', targetType: 'phone', required: false, validated: true },
  { id: 'map-005', integrationId: 'int-001', sourceField: 'status', sourceType: 'picklist', targetField: 'candidateStatus', targetType: 'picklist', transform: 'STATUS_MAP', required: true, validated: false },
];

export const mockWebhookEvents: WebhookEvent[] = [
  {
    id: 'evt-001',
    integrationId: 'int-001',
    eventType: 'candidate.created',
    status: 'success',
    payload: { candidateId: 'cnd-123', name: 'John Doe', email: 'john@example.com' },
    response: { status: 200, message: 'Processed successfully' },
    attempts: 1,
    createdAt: new Date(Date.now() - 10 * 60 * 1000),
    processedAt: new Date(Date.now() - 10 * 60 * 1000 + 150),
  },
  {
    id: 'evt-002',
    integrationId: 'int-001',
    eventType: 'candidate.updated',
    status: 'success',
    payload: { candidateId: 'cnd-124', changes: { status: 'Interview 2' } },
    response: { status: 200 },
    attempts: 1,
    createdAt: new Date(Date.now() - 25 * 60 * 1000),
    processedAt: new Date(Date.now() - 25 * 60 * 1000 + 200),
  },
  {
    id: 'evt-003',
    integrationId: 'int-001',
    eventType: 'job.closed',
    status: 'failed',
    payload: { jobId: 'job-456', reason: 'Position filled' },
    error: 'Timeout: Target system did not respond within 30s',
    attempts: 3,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'evt-004',
    integrationId: 'int-001',
    eventType: 'application.submitted',
    status: 'retrying',
    payload: { applicationId: 'app-789', candidateId: 'cnd-125' },
    error: 'Connection reset by peer',
    attempts: 2,
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
  },
  {
    id: 'evt-005',
    integrationId: 'int-001',
    eventType: 'candidate.stage_changed',
    status: 'pending',
    payload: { candidateId: 'cnd-126', newStage: 'Offer' },
    attempts: 0,
    createdAt: new Date(Date.now() - 2 * 60 * 1000),
  },
];

export const mockIntegrationErrors: IntegrationError[] = [
  {
    id: 'err-001',
    integrationId: 'int-001',
    recordId: 'cnd-200',
    objectType: 'Candidate',
    errorType: 'VALIDATION_ERROR',
    errorMessage: 'Required field "email" is missing',
    payload: { firstName: 'Jane', lastName: 'Smith' },
    retryable: true,
    retryCount: 0,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
  },
  {
    id: 'err-002',
    integrationId: 'int-001',
    recordId: 'job-300',
    objectType: 'Job',
    errorType: 'DUPLICATE_RECORD',
    errorMessage: 'A job with this external ID already exists',
    payload: { externalId: 'SF-JOB-456', title: 'Software Engineer' },
    retryable: false,
    retryCount: 1,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
  },
  {
    id: 'err-003',
    integrationId: 'int-001',
    recordId: 'cnd-201',
    objectType: 'Candidate',
    errorType: 'API_ERROR',
    errorMessage: 'Rate limit exceeded. Try again in 60 seconds.',
    payload: { firstName: 'Bob', lastName: 'Wilson', email: 'bob@test.com' },
    retryable: true,
    retryCount: 2,
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
  },
];

export const mockIntegrationMetrics: IntegrationMetrics = {
  integrationId: 'int-001',
  period: 'Last 7 days',
  totalSyncs: 168,
  successfulSyncs: 162,
  failedSyncs: 6,
  successRate: 96.4,
  avgLatencyMs: 245,
  recordsProcessed: 1847,
  queuedJobs: 3,
  lastError: 'Rate limit exceeded (2 hours ago)',
};
